DIALOG PVM_CONSENT_DIALOG {
  NAME DIALOG_TITLE;

  GROUP {
    COLUMNS 1;

    STATICTEXT { NAME WARNING; }
    GROUP {
      COLUMNS 2;
      SCALE_H;

      CHECKBOX DONT_SHOW { FIT_H; ALIGN_LEFT; NAME DONT_SHOW; }
      BUTTON LEARN_MORE { FIT_H; ALIGN_RIGHT; SIZE 0, 10; NAME LEARN_MORE; }
    }
  }

  DLGGROUP { OK; CANCEL; }
}
