DIALOG PVM_CONSENT_DIALOG {
  NAME PVM_DIALOG_TITLE;

  GROUP {
    COLUMNS 1;

    STATICTEXT { NAME PVM_WARNING; }
    GROUP {
      COLUMNS 1;
      FIT_H;

      BUTTON LEARN_MORE { FIT_H; ALIGN_RIGHT; SIZE 0, 10; NAME LEARN_MORE; }
      CHECKBOX DONT_SHOW { FIT_H; ALIGN_LEFT; NAME DONT_SHOW; }
    }
  }

  DLGGROUP { OK; CANCEL; }
}
