DIALOG zyncdialog {
	NAME DIALOG_TITLE;
	GROUP {
	    BORDERSIZE 8,8,8,8;
		SIZE 500, 0;
		COLUMNS 2;
		
		GROUP {
	      	COLUMNS 1;
			GROUP {
				SIZE 500, 0;
			    SPACE 4,4;
			    BORDERSIZE 8,8,8,8;
			    COLUMNS 2;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME VMS_TITLE;
	
				STATICTEXT { ALIGN_LEFT; NAME VMS_NUM_CAPTION; }
				EDITNUMBERARROWS VMS_NUM { ALIGN_RIGHT; SCALE_H; }

				STATICTEXT { ALIGN_LEFT; NAME VMS_TYPE_CAPTION; }
				COMBOBOX VMS_TYPE {
					ALIGN_RIGHT;
					SCALE_H;
				}
	
				STATICTEXT EST_PRICE { ALIGN_RIGHT; SCALE_H; NAME EST_COST; }
				BUTTON COST_CALC_LINK { ALIGN_RIGHT; SIZE 0, 10; NAME COST_CALC; }
			}

		    GROUP {
				SCALE_H;
				RADIOGROUP {
				    GROUP {
						SCALE_H;
				      	COLUMNS 2;
						BORDERSTYLE BORDER_GROUP_IN;
						NAME PROJ_TITLE;
		
						RADIOGADGET EXISTING_PROJ {
							ALIGN_LEFT;
							NAME EXISTING_PROJ_NAME;
						}
						COMBOBOX EXISTING_PROJ_NAME {
							ALIGN_RIGHT;
							SCALE_H;
							CHILDS {
							}
						}
			
						RADIOGADGET NEW_PROJ { 
							ALIGN_LEFT;
							NAME NEW_PROJ_NAME;
						}
						EDITTEXT NEW_PROJ_NAME { ALIGN_RIGHT; SCALE_H; }
					}
				}
			}

			GROUP {
				SCALE_H;
		      	COLUMNS 1;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME JOB_TITLE;

				GROUP {
					SCALE_H;
			      	COLUMNS 2;
					STATICTEXT { ALIGN_LEFT; NAME JOB_PRIORITY_CAPTION; }
					EDITNUMBERARROWS JOB_PRIORITY { ALIGN_RIGHT; SIZE 30,0; }
				}
		
				GROUP {
					SCALE_H;
			      	COLUMNS 2;
					STATICTEXT { ALIGN_LEFT; NAME OUTPUT_CAPTION; }
					EDITTEXT OUTPUT_DIR { ALIGN_RIGHT; SCALE_H; }
				}
		
				GROUP {
					SCALE_H;
			      	COLUMNS 2;

					GROUP {
				      	COLUMNS 1;
						ALIGN_LEFT; 
						CHECKBOX JUST_UPLOAD { NAME JUST_UPLOAD_CAPTION; }
						CHECKBOX NO_UPLOAD { NAME NO_UPLOAD_CAPTION; }
						CHECKBOX IGN_MISSING_PLUGINS { NAME IGN_MISSING_PLUGINS_CAPTION; }
					}
					
					BUTTON FILES_LIST { ALIGN_RIGHT; SIZE 0,-20; NAME FILES_LIST_CAPTION; }
				}
			}
		}

		GROUP {
	      	COLUMNS 1;
			GROUP {
				SCALE_H;
		      	COLUMNS 1;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME RENDER_TITLE;
		
				GROUP {
					SCALE_H;
			      	COLUMNS 2;
					STATICTEXT { ALIGN_LEFT; NAME RENDERER_CAPTION; }
					COMBOBOX RENDERER {
						ALIGN_RIGHT;
						SCALE_H;
						CHILDS {
							REND_C4D, REND_C4D_NAME;
						}
					}
				}
		
				GROUP {
					SCALE_H;
			      	COLUMNS 2;
			
					STATICTEXT { ALIGN_LEFT; NAME FRAMES_CAPTION; }
					EDITTEXT FRAMES { ALIGN_RIGHT; SIZE 100,0; }
			
					STATICTEXT { ALIGN_LEFT; NAME STEP_CAPTION; }
					EDITNUMBER STEP { ALIGN_RIGHT; SIZE 100,0; }

					STATICTEXT { ALIGN_LEFT; NAME CHUNK_CAPTION; }
					EDITNUMBER CHUNK { ALIGN_RIGHT; SIZE 100,0; }
				}
		
				GROUP {
					SCALE_H;
			      	COLUMNS 2;
			
					STATICTEXT { ALIGN_LEFT; NAME CAMERA_CAPTION; }
					COMBOBOX CAMERA {
						ALIGN_RIGHT;
						SCALE_H;
					}
				}
		
				GROUP {
					SCALE_H;
			      	COLUMNS 4;
			
					STATICTEXT { NAME RESOLUTION_CAPTION; }
					EDITNUMBERARROWS RES_X { SIZE 60,0; }
					STATICTEXT { NAME RESOLUTION_CAPTION2; }
					EDITNUMBERARROWS RES_Y { SIZE 60,0; }
				}
			}


			GROUP {
				SCALE_H;
		      	COLUMNS 1;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME ACCOUNT_TITLE;
		
				STATICTEXT LOGGED_LABEL { SCALE_H; CENTER_H; NAME LOGGED_AS; }
				BUTTON LOGOUT { SCALE_H; NAME LOGOUT_CAPTION; }
			}
		}
	}
	GROUP {
		SCALE_H;
		CENTER_H;
      	COLUMNS 2;
	    BORDERSIZE 16,16,16,16;
		BUTTON CLOSE { SCALE_H; SIZE 0, 20; NAME CANCEL; }
		BUTTON LAUNCH { SCALE_H; SIZE 0, 20; NAME LAUNCH_CAPTION; }
	}
}