DIALOG zyncdialog {
	NAME DIALOG_TITLE;
	GROUP {
	    BORDERSIZE 8,8,8,8;
		SIZE 500, 0;
		COLUMNS 2;
		
		GROUP {
	      	COLUMNS 1;
			GROUP {
				SIZE 500, 0;
			    SPACE 4,4;
			    BORDERSIZE 8,8,8,8;
			    COLUMNS 2;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME VMS_TITLE;
	
				STATICTEXT { ALIGN_LEFT; NAME VMS_NUM_CAPTION; }
				EDITTEXT VMS_NUM { ALIGN_RIGHT; FIT_H; }

				STATICTEXT { ALIGN_LEFT; NAME VMS_TYPE_CAPTION; }
				COMBOBOX VMS_TYPE {
					ALIGN_RIGHT;
					FIT_H;
					CHILDS {
						FOO, FOO_NAME;
					}
				}
	
				STATICTEXT EST_PRICE { ALIGN_RIGHT; FIT_H; NAME EST_COST; }
				STATICTEXT COST_CALC_LINK { ALIGN_RIGHT; FIT_H; NAME COST_CALC; }
	
			}

			RADIOGROUP {
				SIZE 500, 0;
			    GROUP {
					SIZE 500, 0;
			      	COLUMNS 2;
					BORDERSTYLE BORDER_GROUP_IN;
					NAME PROJ_TITLE;
		
					RADIOGADGET EXISTING_PROJ {
						ALIGN_LEFT;
						NAME EXISTING_PROJ_NAME;
					}
					COMBOBOX VMS_TYPE {
						ALIGN_RIGHT;
						FIT_H;
						CHILDS {
							BAR, BAR_NAME;
						}
					}
			
					RADIOGADGET NEW_PROJ { 
						ALIGN_LEFT;
						NAME NEW_PROJ_NAME;
					}
					EDITTEXT NEW_PROJ_NAME { ALIGN_RIGHT; FIT_H; }
				}
			}

			GROUP {
				FIT_H;
		      	COLUMNS 1;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME JOB_TITLE;

				GROUP {
					FIT_H;
			      	COLUMNS 2;
					STATICTEXT { ALIGN_LEFT; NAME JOB_PRIORITY_CAPTION; }
					EDITTEXT JOB_PRIORITY { ALIGN_RIGHT; SIZE 30,0; }
				}
		
				GROUP {
					FIT_H;
			      	COLUMNS 2;
					STATICTEXT { ALIGN_LEFT; NAME OUTPUT_CAPTION; }
					EDITTEXT OUTPUT_DIR { ALIGN_RIGHT; FIT_H; }
				}
		
				CHECKBOX JUST_UPLOAD { ALIGN_LEFT; NAME JUST_UPLOAD_CAPTION; }
				CHECKBOX NO_UPLOAD { ALIGN_LEFT; NAME NO_UPLOAD_CAPTION; }
				CHECKBOX IGN_MISSING_PLUGINS { ALIGN_LEFT; NAME IGN_MISSING_PLUGINS_CAPTION; }
			}
		}

		GROUP {
	      	COLUMNS 1;
			GROUP {
				FIT_H;
		      	COLUMNS 1;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME RENDER_TITLE;
		
				GROUP {
					FIT_H;
			      	COLUMNS 2;
					STATICTEXT { ALIGN_LEFT; NAME RENDERER_CAPTION; }
					COMBOBOX VMS_TYPE {
						ALIGN_RIGHT;
						FIT_H;
						CHILDS {
							REND_C4D, REND_C4D_NAME;
							REND_ARNOLD, REND_ARNOLD_NAME;
						}
					}
					CHECKBOX BAZ { ALIGN_RIGHT; NAME BAZ_NAME; }
				}
		
				GROUP {
					FIT_H;
			      	COLUMNS 2;
			
					STATICTEXT { ALIGN_LEFT; NAME FRAMES_CAPTION; }
					EDITTEXT FRAMES { ALIGN_RIGHT; SIZE 100,0; }
			
					STATICTEXT { ALIGN_LEFT; NAME STEP_CAPTION; }
					EDITTEXT STEP { ALIGN_RIGHT; SIZE 100,0; }

					STATICTEXT { ALIGN_LEFT; NAME CHUNK_CAPTION; }
					EDITTEXT CHUNK { ALIGN_RIGHT; SIZE 100,0; }
				}
		
				GROUP {
					FIT_H;
			      	COLUMNS 2;
			
					STATICTEXT { ALIGN_LEFT; NAME CAMERA_CAPTION; }
					COMBOBOX CAMERA {
						ALIGN_RIGHT;
						FIT_H;
						CHILDS {
							FOO, FOO_NAME;
							BAR, BAR_NAME;
						}
					}
				}
		
				GROUP {
					FIT_H;
			      	COLUMNS 4;
			
					STATICTEXT { NAME RESOLUTION_CAPTION; }
					EDITTEXT RES_X { SIZE 60,0; }
					STATICTEXT { NAME RESOLUTION_CAPTION2; }
					EDITTEXT RES_Y { SIZE 60,0; }
				}
		
				STATICTEXT { ALIGN_LEFT; NAME WHAT_TO_RENDER; }
			}


			GROUP {
				FIT_H;
		      	COLUMNS 1;
				BORDERSTYLE BORDER_GROUP_IN;
				NAME ACCOUNT_TITLE;
		
				BUTTON LOGIN { FIT_H; NAME LOGIN_CAPTION; }
				BUTTON LOGOUT { FIT_H; NAME LOGOUT_CAPTION; }
				STATICTEXT LOGGED_LABEL { FIT_H; CENTER_H; NAME LOGGED_AS; }
				BUTTON LAUNCH { FIT_H; SIZE 0, 20; NAME LAUNCH_CAPTION; }
			}
		}
	}
}